### ISSUE TITLE
Does this plugin works with Gradle v7.3?

### ISSUE THREAD

**Issue by rufik** [nilsjr/gradle-ftp-upload-plugin#20]
I'm using Huawei DevEco IDE for wearables development. It has OHOS HAP plugin which is tied to Gradle v7.3 unfortunetly.
In main app `build.gradle` file I've put lines:
```
apply plugin: 'de.nilsdruyen.gradle-ftp-upload-plugin'
buildscript {
    dependencies {
        ...
        classpath "de.nilsdruyen:gradle-ftp-upload-plugin:0.3.0"
    }
}
```
And in module's `build.gradle` I have:
```
import de.nilsdruyen.gradle.ftp.UploadExtension

configure<UploadExtension> {
    ...
}
```

But when I'm trying to sync&build I'm getting this error:
```
Could not compile build file 'C:\Temp\DevEcoStudioProjects\MyApp1\entry\build.gradle'.
> startup failed:
  build file 'C:\Temp\DevEcoStudioProjects\MyApp1\entry\build.gradle': 43: unable to resolve class configure 
   @ line 43, column 1.
     configure<UploadExtension> {
     ^
```

Is it related to old Gradle version? Or I'm missing something?

**Comment by nilsjr** [comment]
From what I see you applied the plugin only to the root project. You need to apply it to the "entry" module build.gradle 

Just add `apply plugin: "de.nilsdruyen.gradle-ftp-upload-plugin"` or see usage in my pet project [Module build.gradle.kts](https://github.com/nilsjr/WoWMythicPlus/blob/7c908285f66f0ffd8dec42a0ebf088a0d8f5e6da/web/build.gradle.kts#L9)

Additional Gradle plugin portal shows you both plugins DSL and legacy usage
 [Gradle plugin portal](https://plugins.gradle.org/plugin/de.nilsdruyen.gradle-ftp-upload-plugin)

**Comment by nilsjr** [comment]
You also have to switch the extension usage in groovy

`ftpUploadExtension {
    host = findProperty("ftp.host") ?: ""
    port = findProperty("ftp.port").toInteger() ?: 22
    username = findProperty("ftp.username") ?: ""
    password = findProperty("ftp.password") ?: ""
    sourceDir = "$rootProject.projectDir/app"
    targetDir = "/html/testfolder"
}`

I will update the README.md

**Comment by rufik** [comment]
> You also have to switch the extension usage in groovy
> 
> example:
> 
> ```groovy
> ftpUploadExtension {
> ```

That's the case! I had to use `ftpUploadExtension` instead of `configure<UploadExtension>`. Thank you very much :)
