### ISSUE TITLE
Illegal signs in artifact filenames at huawei repo

### ISSUE THREAD

**Issue by rufik** [nilsjr/gradle-ftp-upload-plugin#35]
I've configured plugin (DevEco 3.1 ) in my build.gradle like that:
```
    repositories {
        maven {
            url 'https://repo.huaweicloud.com/repository/maven/'
        }
        maven {
            url 'https://developer.huawei.com/repo/'
        }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        jcenter()
    }
    dependencies {
        ....
        classpath "de.nilsdruyen:gradle-ftp-upload-plugin:0.3.0"
    }
```
but got into troubles:
```
> Could not resolve all files for configuration ':classpath'.
   > Could not find gradle-ftp-upload-plugin-0.3.0.jar (de.nilsdruyen:gradle-ftp-upload-plugin:0.3.0).
     Searched in the following locations:
         https://repo.huaweicloud.com/repository/maven/de/nilsdruyen/gradle-ftp-upload-plugin/0.3.0/gradle-ftp-upload-plugin-0.3.0.jar
```

Well, I've followed the URL and got HTTP 404. So I took a look into parent folder (https://repo.huaweicloud.com/repository/maven/de/nilsdruyen/gradle-ftp-upload-plugin/0.3.0/) and it looks like artifact filename has `"` signs at the beginning and the end: `https://repo.huaweicloud.com/repository/maven/de/nilsdruyen/gradle-ftp-upload-plugin/0.3.0/%22gradle-ftp-upload-plugin-0.3.0.jar%22`
That's why it cannot be found. Could you publish it properly please?

![image](https://github.com/nilsjr/gradle-ftp-upload-plugin/assets/425558/988d1ebf-1957-4a93-9f64-7eb9eddc9fa7)

**Comment by nilsjr** [comment]
Hey @rufik
it is published correctly in the gradle plugin portal. Try to move the gradle url definition higher than the huawei. It is not published on the huaweicloud maven.

Here is the published plugin.
https://plugins.gradle.org/plugin/de.nilsdruyen.gradle-ftp-upload-plugin
https://plugins.gradle.org/m2/de/nilsdruyen/gradle-ftp-upload-plugin/0.3.0/

Or use gradlePluginPortal() like here
https://github.com/nilsjr/WoWMythicPlus/blob/develop/settings.gradle.kts

**Comment by rufik** [comment]
Thanks a lot, moving definition on top just works fine :)
