### ISSUE TITLE
option to clean target directory before upload

### ISSUE THREAD

**Issue by maplat1** [nilsjr/gradle-ftp-upload-plugin#63]
thx for the great work on this plugin

Many of the KMP projects are creating dynamically named assets, so creating a bit of a mess if we just upload the project to a target directory.

Any chance you can either add a dedicated task or a flag "cleanTargetDirectoryBeforeUpload" to the task so we dont have to clean it manually or using some other plugin

thx

**Comment by nilsjr** [comment]
Hey @maplat1,
Thank you for your idea.
I will try either a task to clear it manually or with a field "clearDirectoryBeforeUpload" true/false. Or maybe both :D I think it doesn't hurt.
